VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IFunction"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = True


Option Explicit

Public Function Evaluate(ParamArray Arguments() As Variant) As Variant
End Function

Public Function Run(ParamArray Arguments() As Variant) As IFunction
End Function

Public Function Bind(ParamArray Arguments() As Variant) As IFunction
End Function